### ISSUE TITLE
Promise rejection

### ISSUE THREAD

**Issue by briankaemingk** [lapwat/reCatchable#4]
Hi! I think I'm using it correctly with the selector, but I ran into the following issue (similar to the previous issue).. Thanks!

```
(base) briankaemingk@brians-MacBook-Pro reCatchable % ./index.js -h https://tldp.org/HOWTO/Software-Building-HOWTO.html -s 'a[name*="toc"]'
Found 17 pages in the table of content.
Downloading Building and Installing Software Packages for Linux...
(node:14981) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: 
    at onParseError (internal/url.js:258:9)
    at new URL (internal/url.js:334:5)
    at Object.urlFilter (/Users/briankaemingk/Documents/reCatchable/utils/scraper.js:58:13)
    at Scraper.requestResource (/Users/briankaemingk/Documents/reCatchable/node_modules/website-scraper/lib/scraper.js:204:47)
    at tryCatcher (/Users/briankaemingk/Documents/reCatchable/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/briankaemingk/Documents/reCatchable/node_modules/bluebird/js/release/map.js:68:38)
    at MappingPromiseArray.PromiseArray._iterate (/Users/briankaemingk/Documents/reCatchable/node_modules/bluebird/js/release/promise_array.js:115:31)
    at MappingPromiseArray.init (/Users/briankaemingk/Documents/reCatchable/node_modules/bluebird/js/release/promise_array.js:79:10)
    at MappingPromiseArray._asyncInit (/Users/briankaemingk/Documents/reCatchable/node_modules/bluebird/js/release/map.js:37:10)
    at _drainQueueStep (/Users/briankaemingk/Documents/reCatchable/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/Users/briankaemingk/Documents/reCatchable/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/briankaemingk/Documents/reCatchable/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/briankaemingk/Documents/reCatchable/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14981) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 18)
(node:14981) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(base) briankaemingk@brians-MacBook-Pro reCatchable % 
(base) briankaemingk@brians-MacBook-Pro reCatchable % 
(base) briankaemingk@brians-MacBook-Pro reCatchable % 
(base) briankaemingk@brians-MacBook-Pro reCatchable % ./index.js -h https://tldp.org/HOWTO/Software-Building-HOWTO.html -s 'a[name*="toc"]'
Found 17 pages in the table of content.
Downloading Building and Installing Software Packages for Linux...
(node:15024) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: 
    at onParseError (internal/url.js:258:9)
    at new URL (internal/url.js:334:5)
    at Object.urlFilter (/Users/briankaemingk/Documents/reCatchable/utils/scraper.js:58:13)
    at Scraper.requestResource (/Users/briankaemingk/Documents/reCatchable/node_modules/website-scraper/lib/scraper.js:204:47)
    at tryCatcher (/Users/briankaemingk/Documents/reCatchable/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/briankaemingk/Documents/reCatchable/node_modules/bluebird/js/release/map.js:68:38)
    at MappingPromiseArray.PromiseArray._iterate (/Users/briankaemingk/Documents/reCatchable/node_modules/bluebird/js/release/promise_array.js:115:31)
    at MappingPromiseArray.init (/Users/briankaemingk/Documents/reCatchable/node_modules/bluebird/js/release/promise_array.js:79:10)
    at MappingPromiseArray._asyncInit (/Users/briankaemingk/Documents/reCatchable/node_modules/bluebird/js/release/map.js:37:10)
    at _drainQueueStep (/Users/briankaemingk/Documents/reCatchable/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/Users/briankaemingk/Documents/reCatchable/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/briankaemingk/Documents/reCatchable/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/briankaemingk/Documents/reCatchable/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15024) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 18)
(node:15024) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lapwat** [comment]
Hi, thank you for your feedback, I have pushed a fix :)

Also, I think that you have specified a bad selector:

```html
<h2>
  <a name="toc2">2.</a>                                                     // your selector contains this link with a null href
  <a href="Software-Building-HOWTO-2.html">Unpacking the Files</a>          // you need to select this one only
</h2>
```

Select the links under `h2` and having a `href` attrbute:

```sh
❯ ./index.js -h https://tldp.org/HOWTO/Software-Building-HOWTO.html -s 'h2 > a[href]'
```

Tell me if it works

**Comment by briankaemingk** [comment]
Thanks, that works great! I'll close this.. Is there documentation I can read on the selectors?

**Comment by lapwat** [comment]
Great!

You will find everything you need about the CSS selectors [on this page](https://www.w3schools.com/cssref/css_selectors.asp).
